To demonstrate Discretization by Binning methods 
Distance Binning and Frequency Binning

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Covid_data.csv")
print(df)

     Gender  Age  Co_Morbid  Admit_date Discharge_date  Remdesivir_Given  \
0         M   46          1  01-09-2021     15-09-2021                 0   
1         M   51          1  03-09-2021     15-09-2021                 1   
2         F   82          1  06-09-2021     15-09-2021                 1   
3         M   51          1  08-09-2021     15-09-2021                 0   
4         M   66          1  09-09-2021     15-09-2021                 0   
...     ...  ...        ...         ...            ...               ...   
1227      F   76          1  25-04-2021     26-04-2021                 0   
1228      F   27          0  16-04-2021     26-04-2021                 0   
1229      M   65          1  14-04-2021     25-04-2021                 0   
1230      F   76          1  15-04-2021     24-04-2021                 0   
1231      F   32          0  19-04-2021     24-04-2021                 1   

      DaysOfStay  DischargeType  Covid_Severity Covid_SeverityDescription  \
0         

In [3]:
# 1. Distance binning Or equal width partitioning
# Formula -> interval = (max-min) / Number of Bins 
# number of bins=4
# Let us consider the 'Age' continuous value column for binning
min_value = df['Age'].min()
max_value = df['Age'].max()
print(min_value)
print(max_value)

1
91


In [4]:

# linspace returns evenly spaced numbers over a specified interval. 
# Returns num evenly spaced samples, calculated over the interval [start, stop].
#np.linspace(2.0, 3.0, num=5)
#array([2.  , 2.25, 2.5 , 2.75, 3.  ])
#np.linspace(2.0, 3.0, num=5, endpoint=False)
#array([2. ,  2.2,  2.4,  2.6,  2.8])
#np.linspace(2.0, 3.0, num=5, retstep=True)
#(array([2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)


bins = np.linspace(min_value,max_value,5)
print(bins)

[ 1.  23.5 46.  68.5 91. ]


In [5]:
labels = ['Juvenile', 'Adult', 'Middle Age', 'Senior Citizen'];

In [6]:
# We can use the cut() function to convert the numeric values of the column Age into the categorical values.
# We need to specify the bins and the labels.
df['bins_dist'] = pd.cut(df['Age'], bins=bins, labels=labels, include_lowest=True)
print(df['bins_dist'])
# print(df['bins_dist'].values.tolist())

0                Adult
1           Middle Age
2       Senior Citizen
3           Middle Age
4           Middle Age
             ...      
1227    Senior Citizen
1228             Adult
1229        Middle Age
1230    Senior Citizen
1231             Adult
Name: bins_dist, Length: 1232, dtype: category
Categories (4, object): ['Juvenile' < 'Adult' < 'Middle Age' < 'Senior Citizen']


If you want equal distribution of the items in your bins, use qcut . 
If you want to define your own numeric bin ranges, then use cut

In [12]:
# 2. Frequency Binning
# qcut() - Discretize variable into equal-sized buckets based on rank or based on sample quantiles.

pd.qcut(df['Age'], q=4, precision=1, labels=labels,retbins=True)

#df['bin_freq'] = pd.qcut(df['Age'], q=4, precision=1, labels=labels)
#print(df['bin_freq'])
#print(df['bin_freq'].values.tolist())

(0                Adult
 1                Adult
 2       Senior Citizen
 3                Adult
 4           Middle Age
              ...      
 1227    Senior Citizen
 1228          Juvenile
 1229        Middle Age
 1230    Senior Citizen
 1231          Juvenile
 Name: Age, Length: 1232, dtype: category
 Categories (4, object): ['Juvenile' < 'Adult' < 'Middle Age' < 'Senior Citizen'],
 array([ 1., 37., 54., 66., 91.]))